<a href="https://colab.research.google.com/github/mustafabozkaya/DataScienceBootCamp/blob/master/DHP%C4%B0_DS_Bootcamp/Dhpi_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 1
### Your first day at your new job 👩‍💻👨‍💻

You are starting a new job as a junior software developer in an IT company. 

The company’s HR department asks you to fill out a form, so you start by assigning your personal information to corresponding variables.

📌 Create a variable for your name, surname, age, ID number, place of residence, to specify if you have active health insurance or not, and lastly one for specifying your nationality.


In [ ]:
#Please assign your personal information to variables
my_name="Mustafa"
my_surname="BOZKAYA"
my_age=30
ID_number=369258147
my_nationality="Kurdish"
where_i_live="Gaziantep"
health_insurance=True




In [ ]:
a = "Hello, World!"
print(a[1])

e


In [ ]:
a = "Hello, World!"
print(a[-4])

r


In [ ]:
print(a[-5:-2])

orl


In [ ]:
x = "Python is "
y = "awesome"
z =  x + y
print(z)

Python is awesome


In [ ]:
print(len(z))

17


In [ ]:
z.upper()

'PYTHON IS AWESOME'

In [ ]:
"Hello"=='Hello'

True

In [ ]:
type(z)

str

In [ ]:
x = 36 / 4 * (3 + 2) * 4 + 2
print(x) 

182.0


In [ ]:
x = 36 // 4 * (3 + 2) * 4 + 2
print(x) 

182


In [ ]:
print ("Hello World")

Hello World


In [ ]:
x1=int(5)
x2=5

In [ ]:
type(x1)

int

In [ ]:
type(x2)

int

In [ ]:
2*2**3 # üst işlemi öncelikli

16

In [ ]:
z.strip()

'Python is awesome'

In [ ]:
# Comments in python
"""
sgfgsdfhdfh
"""
#dbsdfbsfdbbpdfbjfsbsjbfıhjslhbslfdhbhsofhbnbşhsşhboşhsjbortshbtroısbnhsrtlnbhısırhnsnıolrsıbh

'\nsgfgsdfhdfh\n'

## Strings Methods

In [ ]:
txt = "She said \"Never let go\"."
print(txt) # She said "Never let go".

She said "Never let go".


In [ ]:

game = "Popular Nintendo Game: Mario Kart"

print("l" in game) # Prints: True
print("x" in game) # Prints: False

True
False


In [ ]:
str = 'yellow'
str[1]     # => 'e'
str[-1]    # => 'w'
str[4:6]   # => 'ow'
str[:4]    # => 'yell'
str[-3:]   # => 'low'

'low'

In [ ]:

str = "hello"
for c in str:
  print(c)

h
e
l
l
o


In [ ]:
length = len("Hello")
print(length)
# Output: 5

5


In [ ]:
colors = ['red', 'yellow', 'green']
print(len(colors))
# Output: 3

3


In [ ]:

msg1 = 'Fred scored {} out of {} points.'
msg1.format(3, 10)
# => 'Fred scored 3 out of 10 points.'


'Fred scored 3 out of 10 points.'

In [ ]:

msg2 = 'Fred {verb} a {adjective} {noun}.'
msg2.format(adjective='fluffy', verb='tickled', noun='hamster')
# => 'Fred tickled a fluffy hamster.'

'Fred tickled a fluffy hamster.'

In [ ]:

greeting = "Welcome To Chili's"

print(greeting.lower())
# Prints: welcome to chili's

welcome to chili's


In [ ]:
text1 = '   apples and oranges   '
text1.strip()       # => 'apples and oranges'



'apples and oranges'

In [ ]:
text2 = '...+...lemons and limes...-...'

# Here we strip just the "." characters
text2.strip('.')    # => '+...lemons and limes...-'



'+...lemons and limes...-'

In [ ]:
# Here we strip both "." and "+" characters
text2.strip('.+')   # => 'lemons and limes...-'



'lemons and limes...-'

In [ ]:
# Here we strip ".", "+", and "-" characters
text2.strip('.+-')  # => 'lemons and limes'

'lemons and limes'

In [ ]:
my_var = "dark knight"
print(my_var.title()) 

# Prints: Dark Knight

Dark Knight


In [ ]:
my_var.upper()

'DARK KNIGHT'

In [ ]:
my_var.lower()

'dark knight'

In [ ]:
text = "Silicon Valley"

print(text.split())     
# Prints: ['Silicon', 'Valley']



['Silicon', 'Valley']


In [ ]:
print(text.split('i'))  
# Prints: ['S', 'l', 'con Valley']

['S', 'l', 'con Valley']


In [ ]:
mountain_name = "Mount Kilimanjaro"
print(mountain_name.find("o")) # Prints 1 in the console.

1


In [ ]:
fruit = "Strawberry"
print(fruit.replace('r', 'R'))

# StRawbeRRy

StRawbeRRy


In [ ]:
x = "-".join(["Codecademy", "is", "awesome"])

print(x) 
# Prints: Codecademy-is-awesome

Codecademy-is-awesome


## Lists and Tuples

In [ ]:
A = ["Brush", "Leuven", 48851964400, 3.14, "Mom"]
A

['Brush', 'Leuven', 48851964400, 3.14, 'Mom']

In [ ]:
A.append("whatever")
A

['Brush', 'Leuven', 48851964400, 3.14, 'Mom', 'whatever']

In [ ]:
A.count("what")

0

In [ ]:
len(A)

6

In [ ]:
aTuple = ("Orange",)
print(type(aTuple))

<class 'tuple'>


In [ ]:
aTuple = ("Orange","what")
print(type(aTuple))

<class 'tuple'>


In [ ]:
atuple=45,"merhaba",12
a,b,c=atuple

In [ ]:
a

45

In [ ]:
b

'merhaba'

In [ ]:
c

12

In [ ]:
lst = [3,4,6,1,2]
lst[1:2] = [7,8]
print(lst)

[3, 7, 8, 6, 1, 2]


In [ ]:
list1=[]*3

In [ ]:
list=[]

## Loops and Range
### Learning Objectives
 * While loop
 * For loop
 * Enumerate
 * Range

 [Loops cheatsheets](https://www.codecademy.com/learn/learn-python-3/modules/learn-python3-loops/cheatsheet)

In [ ]:
list1 = [12, 15, 32, 42, 55, 75, 122, 132, 150, 180, 200]
for i,item in enumerate(list1):
  print(f"{i+1} . item is :{item}")

1 . item is :12
2 . item is :15
3 . item is :32
4 . item is :42
5 . item is :55
6 . item is :75
7 . item is :122
8 . item is :132
9 . item is :150
10 . item is :180
11 . item is :200


In [ ]:
for number in lst:
  print(number*5)

15
35
40
30
5
10


In [ ]:

numbers = [0, 254, 2, -1, 3]

for num in numbers:
  if (num < 0):
    print("Negative number detected!")
    break
  print(num)
  
# 0
# 254
# 2
# Negative number detected!

0
254
2
Negative number detected!


In [ ]:

# List comprehension for the squares of all even numbers between 0 and 9
result = [x**2 for x in range(10) if x % 2 == 0]

print(result)
# [0, 4, 16, 36, 64]

[0, 4, 16, 36, 64]


In [ ]:
for num in range(2,-5,-1):

  print(num, end = ",")

2,1,0,-1,-2,-3,-4,

In [ ]:
x=["abc","def"]
for i in x:
  print(i.upper())

x

ABC
DEF


['abc', 'def']

## Dictionary
 * Dictionary is an unordered collection of key-value pairs.
 * Real word dictionaries are a good analogy to understand them: they  contain a list of items(words), and each item has a key(the word) and  a value(the word's meaning).
 * It generally is used when we have a massive amount of data.
 * It is defined within braces, with each item in the form of key: value pairs.

In [ ]:
sampleDict = {
"class":{"student":{
                    "name":"Mike",
                    "marks":{
                              "physics":70,
                              "history":80
                            }
                    }
        }
}

In [ ]:
len(sampleDict)

1

In [ ]:
d = {"john":40, "peter":45}


In [ ]:
len(d)

2

In [ ]:
list(d.keys())

['john', 'peter']

In [ ]:
list(d.values())

[40, 45]

In [ ]:
list(d.items())

[('john', 40), ('peter', 45)]

In [ ]:
var =10
for i in range(10):
  for j in range(2,10,1):
    if var%2 ==1:
      continue
      var+=1
    
  var+=1
else:
  var+=1
print(var)

21


# Functions, Methods and Packages
## Learning Objectives
 * Functions
 * Packages
 * Python Methods

### Functions

In [ ]:
print("hello world")
input("enter your age")

hello world
enter your age10


'10'

**sum() and round() functions**

In [ ]:
round(2.895,1)

2.9

In [ ]:
round(2.895,2)

2.9

In [ ]:
round(2.895,3)

2.895

In [ ]:
l=[1,2,5,6,8,9,7,5,2,5,6,98]
sum(l)

154

## Methods

In Python, everything is an object (be it a list, string, etc.).

A method in Python is somewhat similar to a function. The only difference is that a method depends on the object while a function is independent of the object.

Can you recall we had used a function len() in the earlier modules? Well, this is a function. len() can be used on lists, tuples, strings, dictionaries, etc., to get the number of elements in them. In comparison, append() is a method associated with a list only. You cannot use the append() method on tuples, strings, or dictionaries. This append() is associated with list data type only.

Objects have various methods associated with them (depending on the type of the object)

In [ ]:
len(l)

12

In [ ]:
l.index(98)

11

In [ ]:
l.count(5)

3

In [ ]:
l.append(123)
l

[1, 2, 5, 6, 8, 9, 7, 5, 2, 5, 6, 98, 123]

## Packages in Python
**In simple terms, Python packages are collections of multiple Python files**

And these Python files are known as modules in Python

If we keep all of our code in the same file, it will result in:

  * Huge code base: Ends up messy
  * Lots of code you won't use
  * Maintenance problem

If we take an example of ourselves, we don't usually store all our files on our computer in the same location. We use a well-organized hierarchy of directories/folders for easier access.

Similar files are kept in the same directory. For example, we may keep all the songs in the "music" directory. Analogous to this, Python has packages for directories and modules for files.

As our application program grows larger with many modules, we place similar modules in one package and different modules in different packages. This makes a project (program) easy to manage and conceptually clear.

Similarly, as a directory can contain subdirectories and files, a Python package can have sub-packages and modules.

Packages are a directory/folder of Python Scripts.

Where each script is a module that performs a specific function.

We can specify functions, methods, and types in a script.

Thousands of packages are available in Python.

**For data science, the commonly used packages are:**

 * Numpy: Working with arrays
 * Matplotlib: Data Visualisation
 * Scikit-learn: ML

### Introduction to Numpy

In [ ]:
import numpy as np
#https://dphi.tech/notebooks/851/manish_kc_06/day-5-notebook-introduction-to-numpy?

In [ ]:
from math import factorial
print(factorial(4))

24


In [ ]:
weights=np.array([[[50, 45],
        [56, 78],
        [78, 89],
        [59, 90],
        [89, 78],
        [69, 70]],

       [[67, 69],
        [89, 70],
        [90, 89],
        [80, 84],
        [89, 59],
        [90, 78]]])

In [ ]:
weights_or = weights.reshape((6,4))
weights_or

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [ ]:
weights_ravel=weights_or.ravel()
weights_ravel

array([50, 45, 56, 78, 78, 89, 59, 90, 89, 78, 69, 70, 67, 69, 89, 70, 90,
       89, 80, 84, 89, 59, 90, 78])

In [ ]:
weights_or

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [ ]:
weights_flat=weights_or.flatten()
weights_flat

array([50, 45, 56, 78, 78, 89, 59, 90, 89, 78, 69, 70, 67, 69, 89, 70, 90,
       89, 80, 84, 89, 59, 90, 78])

In [ ]:
weights_or

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [ ]:
heights=np.array([165, 170, 171, 180, 189, 178])

In [ ]:
heights

array([165, 170, 171, 180, 189, 178])

In [ ]:
print("Accessing single element in 1D array:", heights[2])
print("Accessing single element in 2D array:", weights_or[1][3])

Accessing single element in 1D array: 171
Accessing single element in 2D array: 90


In [ ]:
print("Accessing single element in 1D array:", heights[-4])
print("Accessing single element in 2D array:", weights_or[-5][-1])

Accessing single element in 1D array: 171
Accessing single element in 2D array: 90


In [ ]:
heights[2:3] # The ending value is exlusive

array([171])

In [ ]:
weights_or[ ::]

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [ ]:
weights_or[ :3:2] # start stop step

array([[50, 45, 56, 78],
       [89, 78, 69, 70]])

In [ ]:
weights[:4, 2::]

array([[[78, 89],
        [59, 90],
        [89, 78],
        [69, 70]],

       [[90, 89],
        [80, 84],
        [89, 59],
        [90, 78]]])

In [ ]:
weights[:3, :3, :1]

array([[[50],
        [56],
        [78]],

       [[67],
        [89],
        [90]]])

In [ ]:
weights[:2, -3::]

array([[[59, 90],
        [89, 78],
        [69, 70]],

       [[80, 84],
        [89, 59],
        [90, 78]]])

In [ ]:
from numpy.random import seed
from numpy.random import rand

# Seed random number generator
# Ee can also specify a seed, so that the sequence of random numbers is repeatable
# (if you execute the following code several times, you will get the same random results):
seed(42)

# Generate random numbers between 0-1
values = rand(10)
print(values)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]


In [ ]:
#Write a sentence using the print function to describe yourself using the variables above in the correct data type
print(f" My name is {my_name} {my_surname}  .I am {str(my_age)} years old  and I live in {where_i_live}")


 My name is Mustafa BOZKAYA  .I am 30 years old  and I live in Gaziantep


In [ ]:
#Create the item_list
requirement_list=["laptop","headset","second monitor","mousepad","usb driver","external drive"]


In [ ]:
#Print the list
print(*requirement_list,sep=";")


laptop;headset;second monitor;mousepad;usb driver;external drive
