<a href="https://colab.research.google.com/github/mustafabozkaya/DataScienceBootCamp/blob/master/DHP%C4%B0_DS_Bootcamp/Dhpi_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 1
### Your first day at your new job 👩‍💻👨‍💻

You are starting a new job as a junior software developer in an IT company. 

The company’s HR department asks you to fill out a form, so you start by assigning your personal information to corresponding variables.

📌 Create a variable for your name, surname, age, ID number, place of residence, to specify if you have active health insurance or not, and lastly one for specifying your nationality.


In [ ]:
#Please assign your personal information to variables
my_name="Mustafa"
my_surname="BOZKAYA"
my_age=30
ID_number=369258147
my_nationality="Kurdish"
where_i_live="Gaziantep"
health_insurance=True




In [ ]:
a = "Hello, World!"
print(a[1])

e


In [ ]:
a = "Hello, World!"
print(a[-4])

r


In [ ]:
print(a[-5:-2])

orl


In [ ]:
x = "Python is "
y = "awesome"
z =  x + y
print(z)

Python is awesome


In [ ]:
print(len(z))

17


In [ ]:
z.upper()

'PYTHON IS AWESOME'

In [ ]:
"Hello"=='Hello'

True

In [ ]:
type(z)

str

In [ ]:
x = 36 / 4 * (3 + 2) * 4 + 2
print(x) 

182.0


In [ ]:
x = 36 // 4 * (3 + 2) * 4 + 2
print(x) 

182


In [ ]:
print ("Hello World")

Hello World


In [ ]:
x1=int(5)
x2=5

In [ ]:
type(x1)

int

In [ ]:
type(x2)

int

In [ ]:
2*2**3 # üst işlemi öncelikli

16

In [ ]:
z.strip()

'Python is awesome'

In [ ]:
# Comments in python
"""
sgfgsdfhdfh
"""
#dbsdfbsfdbbpdfbjfsbsjbfıhjslhbslfdhbhsofhbnbşhsşhboşhsjbortshbtroısbnhsrtlnbhısırhnsnıolrsıbh

'\nsgfgsdfhdfh\n'

## Strings Methods

In [ ]:
txt = "She said \"Never let go\"."
print(txt) # She said "Never let go".

She said "Never let go".


In [ ]:

game = "Popular Nintendo Game: Mario Kart"

print("l" in game) # Prints: True
print("x" in game) # Prints: False

True
False


In [ ]:
str = 'yellow'
str[1]     # => 'e'
str[-1]    # => 'w'
str[4:6]   # => 'ow'
str[:4]    # => 'yell'
str[-3:]   # => 'low'

'low'

In [ ]:

str = "hello"
for c in str:
  print(c)

h
e
l
l
o


In [ ]:
length = len("Hello")
print(length)
# Output: 5

5


In [ ]:
colors = ['red', 'yellow', 'green']
print(len(colors))
# Output: 3

3


In [ ]:

msg1 = 'Fred scored {} out of {} points.'
msg1.format(3, 10)
# => 'Fred scored 3 out of 10 points.'


'Fred scored 3 out of 10 points.'

In [ ]:

msg2 = 'Fred {verb} a {adjective} {noun}.'
msg2.format(adjective='fluffy', verb='tickled', noun='hamster')
# => 'Fred tickled a fluffy hamster.'

'Fred tickled a fluffy hamster.'

In [ ]:

greeting = "Welcome To Chili's"

print(greeting.lower())
# Prints: welcome to chili's

welcome to chili's


In [ ]:
text1 = '   apples and oranges   '
text1.strip()       # => 'apples and oranges'



'apples and oranges'

In [ ]:
text2 = '...+...lemons and limes...-...'

# Here we strip just the "." characters
text2.strip('.')    # => '+...lemons and limes...-'



'+...lemons and limes...-'

In [ ]:
# Here we strip both "." and "+" characters
text2.strip('.+')   # => 'lemons and limes...-'



'lemons and limes...-'

In [ ]:
# Here we strip ".", "+", and "-" characters
text2.strip('.+-')  # => 'lemons and limes'

'lemons and limes'

In [ ]:
my_var = "dark knight"
print(my_var.title()) 

# Prints: Dark Knight

Dark Knight


In [ ]:
my_var.upper()

'DARK KNIGHT'

In [ ]:
my_var.lower()

'dark knight'

In [ ]:
text = "Silicon Valley"

print(text.split())     
# Prints: ['Silicon', 'Valley']



['Silicon', 'Valley']


In [ ]:
print(text.split('i'))  
# Prints: ['S', 'l', 'con Valley']

['S', 'l', 'con Valley']


In [ ]:
mountain_name = "Mount Kilimanjaro"
print(mountain_name.find("o")) # Prints 1 in the console.

1


In [ ]:
fruit = "Strawberry"
print(fruit.replace('r', 'R'))

# StRawbeRRy

StRawbeRRy


In [ ]:
x = "-".join(["Codecademy", "is", "awesome"])

print(x) 
# Prints: Codecademy-is-awesome

Codecademy-is-awesome


## Lists and Tuples

In [ ]:
A = ["Brush", "Leuven", 48851964400, 3.14, "Mom"]
A

['Brush', 'Leuven', 48851964400, 3.14, 'Mom']

In [ ]:
A.append("whatever")
A

['Brush', 'Leuven', 48851964400, 3.14, 'Mom', 'whatever']

In [ ]:
A.count("what")

0

In [ ]:
len(A)

6

In [ ]:
aTuple = ("Orange",)
print(type(aTuple))

<class 'tuple'>


In [ ]:
aTuple = ("Orange","what")
print(type(aTuple))

<class 'tuple'>


In [ ]:
atuple=45,"merhaba",12
a,b,c=atuple

In [ ]:
a

45

In [ ]:
b

'merhaba'

In [ ]:
c

12

In [ ]:
lst = [3,4,6,1,2]
lst[1:2] = [7,8]
print(lst)

[3, 7, 8, 6, 1, 2]


In [ ]:
list1=[]*3

In [ ]:
list=[]

## Loops and Range
### Learning Objectives
 * While loop
 * For loop
 * Enumerate
 * Range

 [Loops cheatsheets](https://www.codecademy.com/learn/learn-python-3/modules/learn-python3-loops/cheatsheet)

In [ ]:
list1 = [12, 15, 32, 42, 55, 75, 122, 132, 150, 180, 200]
for i,item in enumerate(list1):
  print(f"{i+1} . item is :{item}")

1 . item is :12
2 . item is :15
3 . item is :32
4 . item is :42
5 . item is :55
6 . item is :75
7 . item is :122
8 . item is :132
9 . item is :150
10 . item is :180
11 . item is :200


In [ ]:
for number in lst:
  print(number*5)

15
35
40
30
5
10


In [ ]:

numbers = [0, 254, 2, -1, 3]

for num in numbers:
  if (num < 0):
    print("Negative number detected!")
    break
  print(num)
  
# 0
# 254
# 2
# Negative number detected!

0
254
2
Negative number detected!


In [ ]:

# List comprehension for the squares of all even numbers between 0 and 9
result = [x**2 for x in range(10) if x % 2 == 0]

print(result)
# [0, 4, 16, 36, 64]

[0, 4, 16, 36, 64]


In [ ]:
for num in range(2,-5,-1):

  print(num, end = ",")

2,1,0,-1,-2,-3,-4,

In [ ]:
x=["abc","def"]
for i in x:
  print(i.upper())

x

ABC
DEF


['abc', 'def']

## Dictionary
 * Dictionary is an unordered collection of key-value pairs.
 * Real word dictionaries are a good analogy to understand them: they  contain a list of items(words), and each item has a key(the word) and  a value(the word's meaning).
 * It generally is used when we have a massive amount of data.
 * It is defined within braces, with each item in the form of key: value pairs.

In [13]:
sampleDict = {
"class":{"student":{
                    "name":"Mike",
                    "marks":{
                              "physics":70,
                              "history":80
                            }
                    }
        }
}

In [14]:
len(sampleDict)

1

In [4]:
d = {"john":40, "peter":45}


In [15]:
len(d)

2

In [17]:
list(d.keys())

['john', 'peter']

In [19]:
list(d.values())

[40, 45]

In [20]:
list(d.items())

[('john', 40), ('peter', 45)]

In [3]:
var =10
for i in range(10):
  for j in range(2,10,1):
    if var%2 ==1:
      continue
      var+=1
    
  var+=1
else:
  var+=1
print(var)

21


# Functions, Methods and Packages
## Learning Objectives
 * Functions
 * Packages
 * Python Methods

### Functions

In [22]:
print("hello world")
input("enter your age")

hello world
enter your age10


'10'

**sum() and round() functions**

In [26]:
round(2.895,1)

2.9

In [27]:
round(2.895,2)

2.9

In [28]:
round(2.895,3)

2.895

In [29]:
l=[1,2,5,6,8,9,7,5,2,5,6,98]
sum(l)

154

## Methods

In Python, everything is an object (be it a list, string, etc.).

A method in Python is somewhat similar to a function. The only difference is that a method depends on the object while a function is independent of the object.

Can you recall we had used a function len() in the earlier modules? Well, this is a function. len() can be used on lists, tuples, strings, dictionaries, etc., to get the number of elements in them. In comparison, append() is a method associated with a list only. You cannot use the append() method on tuples, strings, or dictionaries. This append() is associated with list data type only.

Objects have various methods associated with them (depending on the type of the object)

In [30]:
len(l)

12

In [31]:
l.index(98)

11

In [32]:
l.count(5)

3

In [33]:
l.append(123)
l

[1, 2, 5, 6, 8, 9, 7, 5, 2, 5, 6, 98, 123]

## Packages in Python
**In simple terms, Python packages are collections of multiple Python files**

And these Python files are known as modules in Python

If we keep all of our code in the same file, it will result in:

  * Huge code base: Ends up messy
  * Lots of code you won't use
  * Maintenance problem

If we take an example of ourselves, we don't usually store all our files on our computer in the same location. We use a well-organized hierarchy of directories/folders for easier access.

Similar files are kept in the same directory. For example, we may keep all the songs in the "music" directory. Analogous to this, Python has packages for directories and modules for files.

As our application program grows larger with many modules, we place similar modules in one package and different modules in different packages. This makes a project (program) easy to manage and conceptually clear.

Similarly, as a directory can contain subdirectories and files, a Python package can have sub-packages and modules.

Packages are a directory/folder of Python Scripts.

Where each script is a module that performs a specific function.

We can specify functions, methods, and types in a script.

Thousands of packages are available in Python.

**For data science, the commonly used packages are:**

 * Numpy: Working with arrays
 * Matplotlib: Data Visualisation
 * Scikit-learn: ML

In [46]:
import numpy as np
#https://dphi.tech/notebooks/851/manish_kc_06/day-5-notebook-introduction-to-numpy?

In [35]:
from math import factorial
print(factorial(4))

24


In [39]:
weights=np.array([[[50, 45],
        [56, 78],
        [78, 89],
        [59, 90],
        [89, 78],
        [69, 70]],

       [[67, 69],
        [89, 70],
        [90, 89],
        [80, 84],
        [89, 59],
        [90, 78]]])

In [54]:
weights_or = weights.reshape((6,4))
weights_or

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [55]:
weights_ravel=weights_or.ravel()
weights_ravel

array([50, 45, 56, 78, 78, 89, 59, 90, 89, 78, 69, 70, 67, 69, 89, 70, 90,
       89, 80, 84, 89, 59, 90, 78])

In [56]:
weights_or

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [57]:
weights_flat=weights_or.flatten()
weights_flat

array([50, 45, 56, 78, 78, 89, 59, 90, 89, 78, 69, 70, 67, 69, 89, 70, 90,
       89, 80, 84, 89, 59, 90, 78])

In [58]:
weights_or

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [42]:
heights=np.array([165, 170, 171, 180, 189, 178])

In [43]:
heights

array([165, 170, 171, 180, 189, 178])

In [44]:
print("Accessing single element in 1D array:", heights[2])
print("Accessing single element in 2D array:", weights_or[1][3])

Accessing single element in 1D array: 171
Accessing single element in 2D array: 90


In [45]:
print("Accessing single element in 1D array:", heights[-4])
print("Accessing single element in 2D array:", weights_or[-5][-1])

Accessing single element in 1D array: 171
Accessing single element in 2D array: 90


In [60]:
heights[2:3] # The ending value is exlusive

array([171])

In [69]:
weights_or[ ::]

array([[50, 45, 56, 78],
       [78, 89, 59, 90],
       [89, 78, 69, 70],
       [67, 69, 89, 70],
       [90, 89, 80, 84],
       [89, 59, 90, 78]])

In [79]:
weights_or[ :3:2] # start stop step

array([[50, 45, 56, 78],
       [89, 78, 69, 70]])

In [66]:
weights[:4, 2::]

array([[[78, 89],
        [59, 90],
        [89, 78],
        [69, 70]],

       [[90, 89],
        [80, 84],
        [89, 59],
        [90, 78]]])

In [67]:
weights[:3, :3, :1]

array([[[50],
        [56],
        [78]],

       [[67],
        [89],
        [90]]])

In [80]:
weights[:2, -3::]

array([[[59, 90],
        [89, 78],
        [69, 70]],

       [[80, 84],
        [89, 59],
        [90, 78]]])

In [92]:
from numpy.random import seed
from numpy.random import rand

# Seed random number generator
# Ee can also specify a seed, so that the sequence of random numbers is repeatable
# (if you execute the following code several times, you will get the same random results):
seed(42)

# Generate random numbers between 0-1
values = rand(10)
print(values)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]


###Meet And Greet
Introduce yourself to your new co-workers.

📌 Use a f-string to print "My name is Joey Tribbiani I am 25 years old and I live in London”.

In [ ]:
#Write a sentence using the print function to describe yourself using the variables above in the correct data type
print(f" My name is {my_name} {my_surname}  .I am {str(my_age)} years old  and I live in {where_i_live}")


 My name is Mustafa BOZKAYA  .I am 30 years old  and I live in Gaziantep


### Equipment starter pack
The HR department asks you to list the items you would need to improve your work efficiency

Mandatory:
* Laptop
* Headset
* Second monitor

Optional:
* Mousepad
* USB drive
* External drive


📌 Create a shopping list that contains items above and print it.

In [ ]:
#Create the item_list
requirement_list=["laptop","headset","second monitor","mousepad","usb driver","external drive"]


In [ ]:
#Print the list
print(*requirement_list,sep=";")


laptop;headset;second monitor;mousepad;usb driver;external drive


####What is mandatory and what is optional?

📌 Use list slicing to devide your list in two list: 'mandatory_item_list' and 'optional_item_list' and print both to the screen.

In [ ]:
#Use list slicing to divide the mandatory items
mandatory_items=requirement_list[:3]


In [ ]:
#Use list slicing to divide the optional items
optional_items=requirement_list[:2:-1]


In [ ]:
#Print both to the screen
print(*mandatory_items,sep="-m-")
print(50*"=")
print(optional_items)

laptop-m-headset-m-second monitor
['external drive', 'usb driver', 'mousepad']


#### Go Shopping
Next, you will have to go and purchase these items, the finance department confirmed a budget of $5000.

📌 Assign 5000 to a variable called limit, so you know how much you can spend.

In [ ]:
#Assign the spending limit value to a variable called limit
budget=5000 # $


####Price dictionary

Before you start shopping yo need to find the best items that you can buy within the company budget. 

📌 Prepare a dictionary called “price_sheet” that includes the items as keys and the prices as values.  
 

In [ ]:
#Create a dictionary that contains each item and its price
price_list={
   f"{item}" : (int(i)+10)*150 for i,item in enumerate(requirement_list)
}

print(price_list)


{'laptop': 1500, 'headset': 1650, 'second monitor': 1800, 'mousepad': 1950, 'usb driver': 2100, 'external drive': 2250}


####Shopping functions

You need to define three functions that will help you during shopping.

📌 First, create an empty list that  will be your shopping cart. Here you will add the items you need to purchase.

1. Define a function for both adding items to the cart and removing them from the item_list.

📌 The "add_to_cart" function should take the item name and the quantity to buy as an argument. 

2. Define a function that will create an invoice. 

📌 The "create_invoice" function should calculate the taxes of each item (18%) and add it to the total amount.

3. Define a function for the checkout. 

📌 The "checkout" function should subtract the total amount from the budget and print a statement to inform if the payment was successful. 

In [ ]:
#Initialize the cart list
cart_list=[]

In [ ]:
#Define the "add_to_cart" function
def addTheCart(item,quantity):
  
  cart_list.append((item,quantity))
  requirement_list.remove(item)
  


In [ ]:
#Define the "create_invoice" function
def get_invoice():

  total_amount=0
  total_price=0


  for  c_item,quant in cart_list:
    
        price=price_list[c_item]
        all_price=quant*price
        all_taxe=all_price*0.18
        total_price+=all_price
        total_amount+=(all_price+all_taxe)

        print(f" item :{c_item}   price :{price}  quantity : {quant} \t all taxe(%18*price) : {all_taxe} \t all price(*quantity) :{all_price}  total price(taxe+price) :{all_taxe+all_price}")
        
  
  print(f" total price() : {total_price} \t total taxe(%18*total_price) : {total_amount- total_price} \t  total amount(taxe+price) :{total_amount}")
        


  return total_amount



In [ ]:
#Define the "checkout" function

def checkout_budget():
  global budget
  total_amount=get_invoice()

  if budget==0:
    print("you have no limit")
  elif (total_amount<=budget):
    print( "yes you have all of this items ,your payments total {}  your  budgets {}".format(total_amount,budget))

  else:
    print( "NO, you dont buy all of this items drop some items ,your payments total {} much than budgets {}".format(total_amount,budget))




Let's shop!

In [ ]:
#Call the "add_to_cart" function for each item
 
#Add first item to cart
addTheCart("laptop",1)

 
#Add second item to cart
addTheCart("headset",2)
 
#Add third item to cart
addTheCart("second monitor",1)
 
#Add fourth item to cart
addTheCart("usb driver",2)

#Add fifth item to cart
addTheCart("mousepad",2)

 
#Add last item to cart
addTheCart("external drive",2)
 
#Call the create "checkout" function to pay for all your items 
checkout_budget()


 item :laptop   price :1500  quantity : 1 	 all taxe(%18*price) : 270.0 	 all price(*quantity) :1500  total price(taxe+price) :1770.0
 item :headset   price :1650  quantity : 2 	 all taxe(%18*price) : 594.0 	 all price(*quantity) :3300  total price(taxe+price) :3894.0
 item :second monitor   price :1800  quantity : 1 	 all taxe(%18*price) : 324.0 	 all price(*quantity) :1800  total price(taxe+price) :2124.0
 item :usb driver   price :2100  quantity : 2 	 all taxe(%18*price) : 756.0 	 all price(*quantity) :4200  total price(taxe+price) :4956.0
 item :mousepad   price :1950  quantity : 2 	 all taxe(%18*price) : 702.0 	 all price(*quantity) :3900  total price(taxe+price) :4602.0
 item :external drive   price :2250  quantity : 2 	 all taxe(%18*price) : 810.0 	 all price(*quantity) :4500  total price(taxe+price) :5310.0
 total price() : 19200 	 total taxe(%18*total_price) : 3456.0 	  total amount(taxe+price) :22656.0
NO, you dont buy all of this items drop some items ,your payments total 22

###Game Night

You are back at the office and the HR department organizes a welcome party for new employees. 

You decide to create a Rock-Paper-Scissor game. 

📌 Create a Rock-Paper-Scissor game in which the user plays against the computer. The player will choose one of the actions, and the computer will choose its action randomly.


In [ ]:
#Import the random library
import random

In [ ]:
#create a list containing the three actions of the game.
actions="Rock-Paper-Scissor"

action_list=actions.split("-")

action_list


['Rock', 'Paper', 'Scissor']

In [ ]:
#Set the scores of players to 0
player_score=0
computer_score=0


#Ask the user how many rounds they want to play
rounds=int(input("how many rounds you want to play,enter number"))

#Add a round_counter that is 0 at the beginning
round=0

#Write a while loop and put the game inside
while True:


  #Increase round_counter by and print it
  round+=1
  print("-"*50)
  print(f"round :{round}")
  

  #Select a random action for computer
  computer_choice=random.choice(action_list)
  

  #Ask player to choose an action
  player_choice=input("Select action from list [ paper,rock,scissor]")
  

  #Print the players choices
  print("="*50)
  print("computer choice :{}".format(computer_choice))
  print("player choice :{}".format(player_choice))
  print("="*50)
  



  #tie condition
  if str.lower(computer_choice)==str.lower(player_choice):
    print("wow ,you choice same action;no problem try again ")


  #Remaining conditions
  elif computer_choice.lower()=="scissor":
    if player_choice.lower=="paper":
      computer_score+=1
      print("computer win")
    else:
      player_score+=1
      print("player  win")
  
  elif computer_choice.lower()=="paper":
    if player_choice.lower=="rock":
      computer_score+=1
      print("computer win")
    else:
      player_score+=1
      print("player  win")

  elif computer_choice.lower()=="rock":
    if player_choice.lower=="scissor":
      computer_score+=1
      print("computer win")
    else:
      player_score+=1
      print("player  win")


  #Stop the while loop if the round_counter equals the number of total rounds
  
  if round==rounds:
    break

#Print the outcome of the game by using conditional statements
print("total scores")
print("*"*50)
if computer_score==player_score:
  print("unfourtunatly ,no winner  computer :{computer_score} , player :{ player_score}")
  
  
elif computer_score<player_score:
  print(f"player win : {player_score} :{ computer_score }")
else:
  print(f"computer win : {computer_score} : { player_score}")

print("*"*50)


how many rounds you want to play,enter number1
--------------------------------------------------
round :1
Select action from list [ paper,rock,scissor]rock
computer choice :Scissor
player choice :rock
player  win
total scores
**************************************************
player win : 1 :0
**************************************************


# Your first task 

Rachel asks you to write a program to track the name and revenue each employee brings.  

* Create the "salesperson_revenue" dictionary to see the employee name as a key and the revenue as a value.

  📌 Every employee starts with 0 revenue.
* Define the "enter_revenue" function. 

  📌 The function takes the name and revenue as an argument and updates the salesperson_revenue dictionary.


In [ ]:
#Create salesperson_revenue dictionary








In [ ]:
#Define enter_revenue function



####Try out the functions
* In a while loop ask the user to give the name of the employee and for the revenue 

  📌 If the user enters “quit” the loop should break.

After that, print out the salesperson_revenue dictionary.


In [ ]:
#Asking user employee name as input


In [ ]:
#Print the salesperson_revenue dictionary
